title: Jinhang Wei's Homepage
page-top-title: Jinhang Wei
top-section-bg-text: Computer Science & Bioinformatics
home-subtitle: Jinhang Wei&ISTJ;|&ISTJ;尉金行
copyright-text: '&copy; Jinhang Wei 2023-2024. All Rights Reserved.'
